db {
    username = "postgres"
    password = "12345"
    driver = "org.postgresql.Driver"
    url = "jdbc:postgresql://postgres_container:5432/servlet"
},
jwt {
    salt = "c29tZXJhbmRvbXNhbHQ="
    secret = "MySuperSecretKeyForJWTGeneration12345"
}